// Generate all step .md files for lessons 2-9
// Run: node scripts/generate-steps.mjs
import { writeFileSync } from 'fs';

function md(title, highlight, explanation, codes) {
  let out = `---\ntitle: "${title}"\n`;
  if (highlight) out += `highlight: ${highlight}\n`;
  out += `---\n\n${explanation}\n`;
  for (const [lang, variant, code] of codes) {
    if (code) out += `\n\`\`\`${lang}:${variant}\n${code}\n\`\`\`\n`;
  }
  return out;
}

// ── Lesson 02 ──
const l02 = [
  { file: '01-semantic-tags.md', title: 'Семантические теги HTML5', hl: 'html',
    exp: `# Семантические теги HTML5

Раньше сайты верстали сплошными \`<div>\`. В современном вебе мы используем **смысловые теги:**

- \`<header>\` — шапка сайта (логотип и меню)
- \`<nav>\` — блок навигации
- \`<main>\` — главное содержимое страницы
- \`<section>\` — логический раздел
- \`<footer>\` — подвал сайта

Посмотрите на пример справа — это базовый HTML-каркас с семантическими тегами.`,
    s: { html: `<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>СмартОфис</title>\n</head>\n<body>\n  <header>Шапка сайта</header>\n  <main>Главное содержимое</main>\n  <footer>Подвал сайта</footer>\n</body>\n</html>`,
         css: `body {\n  font-family: 'Inter', sans-serif;\n  color: #222222;\n  line-height: 1.5;\n}\n\nheader, main, footer {\n  padding: 20px;\n  border: 1px dashed #ccc;\n  margin: 10px;\n  border-radius: 4px;\n}\n\nheader { background: #e3f2fd; }\nmain   { background: #fff; min-height: 100px; }\nfooter { background: #f8f9fa; }` }
  },
  { file: '02-reset-container.md', title: 'Сброс стилей и контейнер', hl: 'css',
    exp: `# Сброс стилей и контейнер

### Зачем нужен сброс стилей?
У каждого браузера свои стандартные отступы. Чтобы сайт выглядел одинаково везде:
\`\`\`css
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
\`\`\`

### Класс \`.container\`
Контейнер \`max-width: 1200px\` с \`margin: 0 auto\` центрирует содержимое.

## Задание
Допишите CSS: добавьте сброс стилей (\`*\`) и класс \`.container\`.`,
    s: { html: `<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>СмартОфис</title>\n  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">\n</head>\n<body>\n  <div class="container">\n    <h1>СмартОфис</h1>\n    <p>Контент внутри контейнера (1200px, по центру)</p>\n  </div>\n</body>\n</html>`,
         css: `/* Напишите сброс стилей * { ... } */\n\n\nbody {\n  font-family: 'Inter', sans-serif;\n  color: #222222;\n  background-color: #ffffff;\n  line-height: 1.5;\n}\n\n/* Напишите класс .container */` },
    sol: { css: `* {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\n\nbody {\n  font-family: 'Inter', sans-serif;\n  color: #222222;\n  background-color: #ffffff;\n  line-height: 1.5;\n}\n\n.container {\n  max-width: 1200px;\n  margin: 0 auto;\n  padding: 0 15px;\n}` }
  },
  { file: '03-header.md', title: 'Шапка сайта (header)', hl: 'html',
    exp: `# Шапка сайта

Шапка содержит:
- **Логотип** — текст «СмартОфис», жирный, без подчёркивания
- **Навигация** — ссылки «Главная», «Каталог», кнопка «Войти»

Используем **Flexbox**: \`display: flex; justify-content: space-between\` — логотип слева, меню справа.

## Задание
Допишите HTML: добавьте \`<header>\` с логотипом и навигационным меню.`,
    s: { html: `<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>СмартОфис</title>\n  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">\n</head>\n<body>\n  <!-- Создайте <header class="header"> -->\n  <!-- Внутри: .container > .header-container -->\n  <!-- Логотип: <a class="logo"><span>СмартОфис</span></a> -->\n  <!-- Навигация: <nav> <ul class="nav-list"> ... </ul> </nav> -->\n\n\n  <main class="main">\n    <div class="container">\n      <p>Здесь будет содержимое</p>\n    </div>\n  </main>\n</body>\n</html>`,
         css: `* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: 'Inter', sans-serif; color: #222; background: #fff; line-height: 1.5; display: flex; flex-direction: column; min-height: 100vh; }\n.container { max-width: 1200px; margin: 0 auto; padding: 0 15px; }\n.header { border-bottom: 1px solid #ddd; padding: 18px 0; background: #fff; }\n.header-container { display: flex; justify-content: space-between; align-items: center; }\n.logo { display: flex; align-items: center; gap: 10px; text-decoration: none; color: #222; font-size: 20px; font-weight: 800; }\n.nav-list { display: flex; list-style: none; gap: 12px; align-items: center; }\n.nav-link { text-decoration: none; color: #222; padding: 8px 14px; border-radius: 4px; font-weight: 500; font-size: 14px; }\n.nav-link:hover { color: #007bff; background: #eaf2ff; }\n.nav-link.active { color: #007bff; background: #eaf2ff; }\n.nav-btn { background: #007bff; color: #fff; font-weight: 600; }\n.main { flex: 1; padding: 40px 0; }` },
    sol: { html: `<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>СмартОфис</title>\n  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">\n</head>\n<body>\n  <header class="header">\n    <div class="container header-container">\n      <a href="#" class="logo"><span>СмартОфис</span></a>\n      <nav>\n        <ul class="nav-list">\n          <li><a href="#" class="nav-link active">Главная</a></li>\n          <li><a href="#" class="nav-link">Каталог</a></li>\n          <li><a href="#" class="nav-link nav-btn">Войти</a></li>\n        </ul>\n      </nav>\n    </div>\n  </header>\n\n  <main class="main">\n    <div class="container">\n      <p>Здесь будет содержимое</p>\n    </div>\n  </main>\n</body>\n</html>` }
  },
  { file: '04-hero.md', title: 'Hero-баннер', hl: 'html',
    exp: `# Главный баннер (Hero-секция)

Hero-блок — визитная карточка сайта. Содержит:
- Крупный заголовок с названием «СмартОфис»
- Подзаголовок с описанием
- Метрики: «24/7 Доступ», «от 250 ₽», «0 ₽ Без комиссии»

## Задание
Добавьте \`<section class="hero-section">\` с заголовком, подзаголовком и метриками.`,
    s: { html: `<!DOCTYPE html>\n<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>СмартОфис</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"></head>\n<body>\n  <header class="header"><div class="container header-container"><a href="#" class="logo"><span>СмартОфис</span></a><nav><ul class="nav-list"><li><a href="#" class="nav-link active">Главная</a></li><li><a href="#" class="nav-link">Каталог</a></li><li><a href="#" class="nav-link nav-btn">Войти</a></li></ul></nav></div></header>\n  <main class="main"><div class="container">\n    <!-- Добавьте <section class="hero-section"> -->\n\n  </div></main>\n</body></html>`,
         css: `* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: 'Inter', sans-serif; color: #222; background: #fff; line-height: 1.5; display: flex; flex-direction: column; min-height: 100vh; }\n.container { max-width: 1200px; margin: 0 auto; padding: 0 15px; }\n.header { border-bottom: 1px solid #ddd; padding: 18px 0; }\n.header-container { display: flex; justify-content: space-between; align-items: center; }\n.logo { text-decoration: none; color: #222; font-size: 20px; font-weight: 800; }\n.nav-list { display: flex; list-style: none; gap: 12px; align-items: center; }\n.nav-link { text-decoration: none; color: #222; padding: 8px 14px; border-radius: 4px; font-weight: 500; font-size: 14px; }\n.nav-link.active { color: #007bff; background: #eaf2ff; }\n.nav-btn { background: #007bff; color: #fff; font-weight: 600; }\n.main { flex: 1; padding: 40px 0; }\n.hero-section { padding: 20px 0 50px 0; }\n.hero-title { font-size: 64px; line-height: 0.95; letter-spacing: -0.04em; font-weight: 800; margin-bottom: 25px; }\n.brand-highlight { color: #007bff; }\n.hero-bottom { border-top: 2px solid #222; padding-top: 20px; display: flex; justify-content: space-between; align-items: center; gap: 40px; }\n.hero-subtitle { font-size: 17px; color: #555; max-width: 600px; }\n.hero-metrics { display: flex; gap: 25px; }\n.metric-item { display: flex; flex-direction: column; }\n.metric-val { font-size: 20px; font-weight: 800; color: #007bff; }\n.metric-lbl { font-size: 12px; color: #777; }` },
    sol: { html: `<!DOCTYPE html>\n<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>СмартОфис</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"></head>\n<body>\n  <header class="header"><div class="container header-container"><a href="#" class="logo"><span>СмартОфис</span></a><nav><ul class="nav-list"><li><a href="#" class="nav-link active">Главная</a></li><li><a href="#" class="nav-link">Каталог</a></li><li><a href="#" class="nav-link nav-btn">Войти</a></li></ul></nav></div></header>\n  <main class="main"><div class="container">\n    <section class="hero-section">\n      <h1 class="hero-title">Портал бронирования офисных комнат <span class="brand-highlight">«СмартОфис»</span></h1>\n      <div class="hero-bottom">\n        <p class="hero-subtitle">Удобный выбор и быстрое бронирование рабочих пространств</p>\n        <div class="hero-metrics">\n          <div class="metric-item"><span class="metric-val">24/7</span><span class="metric-lbl">Доступ</span></div>\n          <div class="metric-item"><span class="metric-val">от 250 ₽</span><span class="metric-lbl">Аренда</span></div>\n          <div class="metric-item"><span class="metric-val">0 ₽</span><span class="metric-lbl">Без комиссии</span></div>\n        </div>\n      </div>\n    </section>\n  </div></main>\n</body></html>` }
  },
  { file: '05-footer.md', title: 'Подвал сайта (footer)', hl: 'html',
    exp: `# Подвал сайта

Подвал (\`<footer>\`) содержит:
- Название компании и копирайт
- Контакты: email и телефон

Используем \`margin-top: auto\` чтобы подвал прижимался к низу страницы.

## Задание
Добавьте \`<footer>\` с контактной информацией.`,
    s: { html: `<!DOCTYPE html>\n<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>СмартОфис</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"></head>\n<body>\n  <header class="header"><div class="container header-container"><a href="#" class="logo"><span>СмартОфис</span></a></div></header>\n  <main class="main"><div class="container"><h1>Содержимое</h1></div></main>\n  <!-- Добавьте <footer class="footer"> с контактами -->\n\n</body></html>`,
         css: `* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: 'Inter', sans-serif; color: #222; background: #fff; line-height: 1.5; display: flex; flex-direction: column; min-height: 100vh; }\n.container { max-width: 1200px; margin: 0 auto; padding: 0 15px; }\n.header { border-bottom: 1px solid #ddd; padding: 18px 0; }\n.header-container { display: flex; justify-content: space-between; align-items: center; }\n.logo { text-decoration: none; color: #222; font-size: 20px; font-weight: 800; }\n.main { flex: 1; padding: 40px 0; }\n.footer { background: #f8f9fa; border-top: 1px solid #ddd; padding: 25px 0; margin-top: auto; }\n.footer-container { display: flex; justify-content: space-between; align-items: center; }\n.footer-contacts a { color: #007bff; text-decoration: none; }` },
    sol: { html: `<!DOCTYPE html>\n<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>СмартОфис</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"></head>\n<body>\n  <header class="header"><div class="container header-container"><a href="#" class="logo"><span>СмартОфис</span></a></div></header>\n  <main class="main"><div class="container"><h1>Содержимое</h1></div></main>\n  <footer class="footer">\n    <div class="container footer-container">\n      <div><p><strong>СмартОфис</strong> — Сервис бронирования</p><p>© 2026 Все права защищены.</p></div>\n      <div class="footer-contacts"><p>Email: <a href="mailto:info@smartoffice.ru">info@smartoffice.ru</a></p><p>Тел: <a href="tel:+78005553535">+7 (800) 555-35-35</a></p></div>\n    </div>\n  </footer>\n</body></html>` }
  },
];

// Helper: write step file
function writeStep(dir, file, title, hl, exp, start, solution) {
  const s = start || {};
  const sol = { ...s, ...(solution || {}) };
  const codes = [];
  for (const lang of ['html', 'css', 'js']) {
    if (s[lang]) codes.push([lang, 'start', s[lang]]);
  }
  for (const lang of ['html', 'css', 'js']) {
    if (sol[lang]) codes.push([lang, 'solution', sol[lang]]);
  }
  writeFileSync(`content/lessons/${dir}/${file}`, md(title, hl, exp, codes));
}

// Write lesson 02 steps
for (const step of l02) {
  writeStep('02-markup', step.file, step.title, step.hl, step.exp, step.s, step.sol);
}

// ── Lesson 03: Flexbox ──
writeStep('03-flexbox', '01-what-is-flexbox.md', 'Что такое Flexbox?', 'css',
  `# Что такое Flexbox?\n\nFlexbox — инструмент CSS для гибкой раскладки:\n\n- \`display: flex\` — включает режим контейнера\n- \`flex-wrap: wrap\` — перенос элементов\n- \`gap: 20px\` — промежуток между элементами\n\nПопробуйте изменить \`gap\` или убрать \`flex-wrap\`!`,
  { html: `<div class="demo-flex">\n  <div class="box">1</div>\n  <div class="box">2</div>\n  <div class="box">3</div>\n  <div class="box">4</div>\n  <div class="box">5</div>\n  <div class="box">6</div>\n</div>`,
    css: `.demo-flex { display: flex; flex-wrap: wrap; gap: 20px; padding: 20px; }\n.box { width: 150px; height: 100px; background: #007bff; color: #fff; display: flex; align-items: center; justify-content: center; font-family: 'Inter', sans-serif; font-size: 24px; font-weight: 700; border-radius: 6px; }` });

writeStep('03-flexbox', '02-room-card.md', 'Верстка карточки комнаты', 'html',
  `# Карточка комнаты\n\nКаждая карточка содержит:\n1. **Фото** — блок с фиксированной высотой\n2. **Контент** — название, оснащение, цена\n3. **Футер** — цена слева, кнопки справа\n\n## Задание\nДобавьте содержимое карточки: название, оснащение, цену.`,
  { html: `<div style="padding:20px;font-family:'Inter',sans-serif;">\n  <div class="room-card">\n    <div class="card-img-wrap">Фото</div>\n    <div class="card-content">\n      <!-- Добавьте содержимое -->\n    </div>\n  </div>\n</div>`,
    css: `.room-card { width:373px; border:1px solid #ddd; border-radius:6px; overflow:hidden; background:#fff; display:flex; flex-direction:column; font-family:'Inter',sans-serif; }\n.card-img-wrap { width:100%; height:200px; background:#f0f4f8; display:flex; align-items:center; justify-content:center; color:#aaa; }\n.card-content { padding:15px; display:flex; flex-direction:column; flex:1; }\n.card-title { font-size:18px; font-weight:700; margin-bottom:10px; }\n.card-equipment { list-style:none; margin-bottom:15px; }\n.card-equipment li { font-size:13px; color:#555; margin-bottom:4px; }\n.card-footer { display:flex; justify-content:space-between; align-items:center; border-top:1px solid #eee; padding-top:10px; }\n.card-price { font-size:18px; font-weight:700; }\n.card-price span { font-size:13px; font-weight:400; color:#666; }\n.btn { display:inline-block; padding:8px 16px; font-size:14px; font-weight:600; border-radius:4px; text-decoration:none; cursor:pointer; border:none; }\n.btn-primary { background:#007bff; color:#fff; }` },
  { html: `<div style="padding:20px;font-family:'Inter',sans-serif;">\n  <div class="room-card">\n    <div class="card-img-wrap">Мини-офис Focus</div>\n    <div class="card-content">\n      <h3 class="card-title">Мини-офис Focus</h3>\n      <ul class="card-equipment"><li>Wi-Fi 500 Мбит/с</li><li>4K Монитор</li><li>Эргономичное кресло</li></ul>\n      <div class="card-footer">\n        <div class="card-price">450 ₽ <span>/ час</span></div>\n        <a href="#" class="btn btn-primary">Забронировать</a>\n      </div>\n    </div>\n  </div>\n</div>` });

writeStep('03-flexbox', '03-grid.md', 'Сетка из 3 карточек', 'html',
  `# Сетка из 3 карточек\n\n3 карточки + 2 gap по 20px = 1200px контейнер.\n\n## Задание\nДобавьте ещё 2 карточки: Конференц-зал Alpha (1200₽) и Опенспейс Hub (250₽).`,
  { html: `<div style="padding:20px;font-family:'Inter',sans-serif;">\n  <h2 style="text-align:center;margin-bottom:20px;">Популярные офисные комнаты</h2>\n  <div class="rooms-grid">\n    <div class="room-card"><div class="card-img-wrap">Focus</div><div class="card-content"><h3 class="card-title">Мини-офис Focus</h3><ul class="card-equipment"><li>Wi-Fi</li><li>Монитор</li></ul><div class="card-footer"><div class="card-price">450 ₽ <span>/ час</span></div><a href="#" class="btn btn-primary">Забронировать</a></div></div></div>\n    <!-- Добавьте ещё 2 карточки -->\n  </div>\n</div>`,
    css: `.rooms-grid { display:flex; flex-wrap:wrap; gap:20px; }\n.room-card { width:373px; border:1px solid #ddd; border-radius:6px; overflow:hidden; background:#fff; display:flex; flex-direction:column; }\n.card-img-wrap { width:100%; height:200px; background:#f0f4f8; display:flex; align-items:center; justify-content:center; color:#aaa; }\n.card-content { padding:15px; display:flex; flex-direction:column; flex:1; }\n.card-title { font-size:18px; font-weight:700; margin-bottom:10px; }\n.card-equipment { list-style:none; margin-bottom:15px; flex:1; }\n.card-equipment li { font-size:13px; color:#555; margin-bottom:4px; }\n.card-footer { display:flex; justify-content:space-between; align-items:center; border-top:1px solid #eee; padding-top:10px; }\n.card-price { font-size:18px; font-weight:700; }\n.card-price span { font-size:13px; color:#666; font-weight:400; }\n.btn { display:inline-block; padding:8px 16px; font-size:14px; font-weight:600; border-radius:4px; text-decoration:none; cursor:pointer; border:none; }\n.btn-primary { background:#007bff; color:#fff; }` },
  { html: `<div style="padding:20px;font-family:'Inter',sans-serif;">\n  <h2 style="text-align:center;margin-bottom:20px;">Популярные офисные комнаты</h2>\n  <div class="rooms-grid">\n    <div class="room-card"><div class="card-img-wrap">Focus</div><div class="card-content"><h3 class="card-title">Мини-офис Focus</h3><ul class="card-equipment"><li>Wi-Fi</li><li>Монитор</li></ul><div class="card-footer"><div class="card-price">450 ₽ <span>/ час</span></div><a href="#" class="btn btn-primary">Забронировать</a></div></div></div>\n    <div class="room-card"><div class="card-img-wrap">Alpha</div><div class="card-content"><h3 class="card-title">Конференц-зал Alpha</h3><ul class="card-equipment"><li>Проектор</li><li>Спикерфон</li></ul><div class="card-footer"><div class="card-price">1200 ₽ <span>/ час</span></div><a href="#" class="btn btn-primary">Забронировать</a></div></div></div>\n    <div class="room-card"><div class="card-img-wrap">Hub</div><div class="card-content"><h3 class="card-title">Опенспейс Hub</h3><ul class="card-equipment"><li>Стол</li><li>Wi-Fi</li></ul><div class="card-footer"><div class="card-price">250 ₽ <span>/ час</span></div><a href="#" class="btn btn-primary">Забронировать</a></div></div></div>\n  </div>\n</div>` });

// ── Lessons 04-09: one step each for now (expandable later) ──
const simple = [
  { dir: '04-js-dom', file: '01-dom-intro.md', title: 'Что такое DOM?', hl: 'js',
    exp: `# Что такое DOM?\n\nБраузер строит **DOM-дерево** из HTML.\n\n\`\`\`javascript\ndocument.querySelector('h1')      // находит первый <h1>\ndocument.querySelectorAll('.link') // находит все .link\n\`\`\`\n\nНажмите кнопку — JavaScript меняет текст через DOM!`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;">\n  <h1 id="title">Привет, DOM!</h1>\n  <p id="info">Нажмите кнопку</p>\n  <button id="changeBtn" style="margin-top:15px;padding:10px 20px;background:#007bff;color:#fff;border:none;border-radius:4px;cursor:pointer;">Изменить</button>\n</div>`,
         js: `document.addEventListener('DOMContentLoaded', () => {\n  const btn = document.getElementById('changeBtn');\n  const info = document.getElementById('info');\n  btn.addEventListener('click', () => {\n    info.textContent = 'JavaScript изменил текст!';\n    info.style.color = '#28a745';\n    info.style.fontWeight = '700';\n  });\n});` } },
  { dir: '04-js-dom', file: '02-classlist.md', title: 'querySelectorAll и classList', hl: 'js',
    exp: `# querySelectorAll и classList\n\n## Задание\nНапишите код: при клике на ссылку добавьте ей \`.active\` и уберите у остальных.`,
    s: { html: `<nav style="padding:20px;font-family:'Inter',sans-serif;"><ul class="nav-list"><li><a href="#" class="nav-link active">Главная</a></li><li><a href="#" class="nav-link">Каталог</a></li><li><a href="#" class="nav-link">Контакты</a></li></ul></nav>`,
         css: `.nav-list { display:flex; list-style:none; gap:8px; }\n.nav-link { text-decoration:none; color:#222; padding:8px 14px; border-radius:4px; font-weight:500; font-size:14px; transition:all 0.2s; }\n.nav-link:hover { color:#007bff; background:#eaf2ff; }\n.nav-link.active { color:#007bff; background:#eaf2ff; font-weight:600; }`,
         js: `document.addEventListener('DOMContentLoaded', () => {\n  const links = document.querySelectorAll('.nav-link');\n  links.forEach(link => {\n    link.addEventListener('click', (e) => {\n      e.preventDefault();\n      // Уберите .active у всех, добавьте к нажатой\n    });\n  });\n});` },
    sol: { js: `document.addEventListener('DOMContentLoaded', () => {\n  const links = document.querySelectorAll('.nav-link');\n  links.forEach(link => {\n    link.addEventListener('click', (e) => {\n      e.preventDefault();\n      links.forEach(l => l.classList.remove('active'));\n      link.classList.add('active');\n    });\n  });\n});` } },
  { dir: '05-catalog', file: '01-data-array.md', title: 'Массив объектов', hl: 'js',
    exp: `# Массив объектов\n\n## Задание\nСоздайте массив \`OFFICE_ROOMS\` с 3 комнатами.`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;"><h2>Данные комнат</h2><pre id="output" style="background:#f5f5f5;padding:15px;border-radius:6px;margin-top:15px;font-size:13px;">Ожидание...</pre></div>`,
         js: `const OFFICE_ROOMS = [\n  // Добавьте данные: { id, title, pricePerHour, equipment:[] }\n];\n\ndocument.addEventListener('DOMContentLoaded', () => {\n  document.getElementById('output').textContent = JSON.stringify(OFFICE_ROOMS, null, 2);\n});` },
    sol: { js: `const OFFICE_ROOMS = [\n  { id:'focus-1', title:'Мини-офис Focus', pricePerHour:450, equipment:['Wi-Fi','Монитор','Кресло'] },\n  { id:'alpha-2', title:'Конференц-зал Alpha', pricePerHour:1200, equipment:['Проектор','Спикерфон'] },\n  { id:'hub-3', title:'Опенспейс Hub', pricePerHour:250, equipment:['Стол','Wi-Fi'] },\n];\n\ndocument.addEventListener('DOMContentLoaded', () => {\n  document.getElementById('output').textContent = JSON.stringify(OFFICE_ROOMS, null, 2);\n});` } },
  { dir: '05-catalog', file: '02-render-catalog.md', title: 'Динамический каталог (map)', hl: 'js',
    exp: `# Генерация карточек через map()\n\n## Задание\nНапишите \`renderCatalog()\` используя \`OFFICE_ROOMS.map(...).join('')\`.`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;"><h2 style="text-align:center;margin-bottom:20px;">Каталог</h2><div class="rooms-grid" id="catalogContainer"></div></div>`,
         css: `.rooms-grid { display:flex; flex-wrap:wrap; gap:20px; }\n.room-card { width:350px; border:1px solid #ddd; border-radius:6px; overflow:hidden; }\n.card-img-wrap { height:160px; background:#f0f4f8; display:flex; align-items:center; justify-content:center; color:#aaa; }\n.card-content { padding:15px; }\n.card-title { font-size:17px; font-weight:700; margin-bottom:8px; }\n.card-equipment { list-style:none; margin-bottom:12px; }\n.card-equipment li { font-size:13px; color:#555; margin-bottom:3px; }\n.card-footer { display:flex; justify-content:space-between; align-items:center; border-top:1px solid #eee; padding-top:10px; }\n.card-price { font-size:17px; font-weight:700; }\n.card-price span { font-size:13px; color:#666; }\n.btn { padding:8px 16px; font-size:13px; font-weight:600; border-radius:4px; border:none; cursor:pointer; text-decoration:none; }\n.btn-primary { background:#007bff; color:#fff; }`,
         js: `const OFFICE_ROOMS = [\n  { id:'focus-1', title:'Мини-офис Focus', pricePerHour:450, equipment:['Wi-Fi','Монитор','Кресло'] },\n  { id:'alpha-2', title:'Конференц-зал Alpha', pricePerHour:1200, equipment:['Проектор','Спикерфон'] },\n  { id:'hub-3', title:'Опенспейс Hub', pricePerHour:250, equipment:['Стол','Wi-Fi'] },\n];\n\nfunction renderCatalog() {\n  const container = document.getElementById('catalogContainer');\n  if (!container) return;\n  // Используйте OFFICE_ROOMS.map(...).join('')\n}\n\ndocument.addEventListener('DOMContentLoaded', renderCatalog);` },
    sol: { js: `const OFFICE_ROOMS = [\n  { id:'focus-1', title:'Мини-офис Focus', pricePerHour:450, equipment:['Wi-Fi','Монитор','Кресло'] },\n  { id:'alpha-2', title:'Конференц-зал Alpha', pricePerHour:1200, equipment:['Проектор','Спикерфон'] },\n  { id:'hub-3', title:'Опенспейс Hub', pricePerHour:250, equipment:['Стол','Wi-Fi'] },\n];\n\nfunction renderCatalog() {\n  const container = document.getElementById('catalogContainer');\n  if (!container) return;\n  container.innerHTML = OFFICE_ROOMS.map(room => \`<div class="room-card"><div class="card-img-wrap">\${room.title}</div><div class="card-content"><h3 class="card-title">\${room.title}</h3><ul class="card-equipment">\${room.equipment.map(e => \`<li>\${e}</li>\`).join('')}</ul><div class="card-footer"><div class="card-price">\${room.pricePerHour} ₽ <span>/ час</span></div><a href="#" class="btn btn-primary">Забронировать</a></div></div></div>\`).join('');\n}\n\ndocument.addEventListener('DOMContentLoaded', renderCatalog);` } },
  { dir: '06-forms', file: '01-login.md', title: 'preventDefault и формы', hl: 'js',
    exp: `# Перехват отправки формы\n\n\`e.preventDefault()\` останавливает перезагрузку страницы.\n\nПопробуйте: логин \`admin\`, пароль \`12345\`.`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;"><div class="form-card"><h2 style="margin-bottom:16px;">Вход</h2><form id="loginForm"><div class="form-group"><label class="form-label">Логин</label><input type="text" id="login" class="form-control" placeholder="admin"></div><div class="form-group"><label class="form-label">Пароль</label><input type="password" id="password" class="form-control" placeholder="12345"></div><div id="loginAlert" class="form-alert" style="display:none;"></div><button type="submit" class="btn btn-primary" style="width:100%">Войти</button></form></div></div>`,
         css: `.form-card { background:#fff; border:1px solid #ddd; border-radius:8px; padding:24px; max-width:400px; }\n.form-group { margin-bottom:14px; }\n.form-label { display:block; font-size:13px; font-weight:600; margin-bottom:5px; color:#444; }\n.form-control { width:100%; padding:10px 12px; font-size:14px; border:1px solid #ddd; border-radius:4px; font-family:inherit; }\n.form-control:focus { outline:none; border-color:#007bff; }\n.form-alert { padding:10px 14px; border-radius:4px; font-size:13px; margin-bottom:14px; }\n.alert-danger { background:#f8d7da; color:#721c24; }\n.alert-success { background:#d4edda; color:#155724; }\n.btn { padding:10px 16px; font-size:14px; font-weight:600; border-radius:4px; border:none; cursor:pointer; }\n.btn-primary { background:#007bff; color:#fff; }`,
         js: `document.addEventListener('DOMContentLoaded', () => {\n  const form = document.getElementById('loginForm');\n  form.addEventListener('submit', (e) => {\n    e.preventDefault();\n    const login = document.getElementById('login').value.trim();\n    const pass = document.getElementById('password').value.trim();\n    const alert = document.getElementById('loginAlert');\n    if (login === 'admin' && pass === '12345') {\n      alert.textContent = 'Успешный вход!';\n      alert.className = 'form-alert alert-success';\n    } else {\n      alert.textContent = 'Неверный логин или пароль';\n      alert.className = 'form-alert alert-danger';\n    }\n    alert.style.display = 'block';\n  });\n});` } },
  { dir: '07-slider', file: '01-slider.md', title: 'Слайдер с автопрокруткой', hl: 'js',
    exp: `# Слайдер\n\nВсе слайды через \`position: absolute; opacity: 0\`. Активный — \`opacity: 1\`.\n\nАвтопрокрутка через \`setInterval(next, 3000)\`.`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;"><div class="slider">\n  <div class="slide active" style="background:#2d5f8a;"><div class="slide-text"><h3>Слайд 1</h3></div></div>\n  <div class="slide" style="background:#4a8c5c;"><div class="slide-text"><h3>Слайд 2</h3></div></div>\n  <div class="slide" style="background:#8a6b2d;"><div class="slide-text"><h3>Слайд 3</h3></div></div>\n  <div class="slide" style="background:#6b2d8a;"><div class="slide-text"><h3>Слайд 4</h3></div></div>\n  <button class="slider-btn prev">‹</button>\n  <button class="slider-btn next">›</button>\n  <div class="dots"><span class="dot active"></span><span class="dot"></span><span class="dot"></span><span class="dot"></span></div>\n</div></div>`,
         css: `.slider { position:relative; width:100%; height:300px; border-radius:8px; overflow:hidden; }\n.slide { position:absolute; inset:0; opacity:0; transition:opacity .3s; display:flex; align-items:center; justify-content:center; }\n.slide.active { opacity:1; }\n.slide-text { color:#fff; text-align:center; }\n.slide-text h3 { font-size:28px; font-weight:800; }\n.slider-btn { position:absolute; top:50%; transform:translateY(-50%); width:40px; height:40px; border-radius:50%; border:none; background:rgba(255,255,255,.2); color:#fff; font-size:22px; cursor:pointer; }\n.prev { left:12px; } .next { right:12px; }\n.dots { position:absolute; bottom:14px; left:50%; transform:translateX(-50%); display:flex; gap:6px; }\n.dot { width:10px; height:10px; border-radius:50%; background:rgba(255,255,255,.4); cursor:pointer; }\n.dot.active { background:#fff; }`,
         js: `function initSlider() {\n  const slides = document.querySelectorAll('.slide');\n  const dots = document.querySelectorAll('.dot');\n  const prevBtn = document.querySelector('.prev');\n  const nextBtn = document.querySelector('.next');\n  if (!slides.length) return;\n  let current = 0, timerId = null;\n  function show(i) {\n    if (i >= slides.length) current = 0;\n    else if (i < 0) current = slides.length - 1;\n    else current = i;\n    slides.forEach((s, idx) => s.classList.toggle('active', idx === current));\n    dots.forEach((d, idx) => d.classList.toggle('active', idx === current));\n  }\n  function startAuto() { if(timerId) clearInterval(timerId); timerId = setInterval(() => show(current+1), 3000); }\n  nextBtn.addEventListener('click', () => { show(current+1); startAuto(); });\n  prevBtn.addEventListener('click', () => { show(current-1); startAuto(); });\n  dots.forEach((d, i) => d.addEventListener('click', () => { show(i); startAuto(); }));\n  startAuto();\n}\ndocument.addEventListener('DOMContentLoaded', initSlider);` } },
  { dir: '08-search', file: '01-search.md', title: 'Живой поиск (filter)', hl: 'js',
    exp: `# Живой поиск\n\n\`filter()\` + \`toLowerCase().includes()\`\n\nПопробуйте поискать «Focus» или «Alpha»!`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;">\n<input type="text" id="searchInput" placeholder="Поиск..." style="width:100%;padding:10px;border:1px solid #ddd;border-radius:4px;font-size:14px;margin-bottom:20px;">\n<div id="results"></div>\n</div>`,
         css: `.room-item { padding:12px 16px; border:1px solid #ddd; border-radius:6px; margin-bottom:8px; display:flex; justify-content:space-between; align-items:center; font-family:'Inter',sans-serif; }\n.room-item .name { font-weight:600; }\n.room-item .price { color:#007bff; font-weight:700; }`,
         js: `const ROOMS = [\n  { title:'Мини-офис Focus', price:450 },\n  { title:'Конференц-зал Alpha', price:1200 },\n  { title:'Опенспейс Hub', price:250 },\n  { title:'Переговорная Delta', price:800 },\n  { title:'VIP-кабинет Director', price:2000 },\n];\nfunction render(rooms) {\n  const el = document.getElementById('results');\n  if (!rooms.length) { el.innerHTML = '<p style="color:#999">Не найдено</p>'; return; }\n  el.innerHTML = rooms.map(r => '<div class="room-item"><span class="name">' + r.title + '</span><span class="price">' + r.price + ' ₽/ч</span></div>').join('');\n}\ndocument.addEventListener('DOMContentLoaded', () => {\n  render(ROOMS);\n  document.getElementById('searchInput').addEventListener('input', (e) => {\n    render(ROOMS.filter(r => r.title.toLowerCase().includes(e.target.value.toLowerCase().trim())));\n  });\n});` } },
  { dir: '08-search', file: '02-calculator.md', title: 'Калькулятор бронирования', hl: 'js',
    exp: `# Калькулятор стоимости\n\nПри изменении комнаты или часов мгновенно пересчитываем итог.`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;"><div class="form-card"><h2 style="margin-bottom:16px;">Бронирование</h2><form id="bookingForm"><div class="form-group"><label class="form-label">Комната</label><select id="roomSelect" class="form-control"></select></div><div class="form-group"><label class="form-label">Часы</label><input type="number" id="hours" class="form-control" min="1" max="24" value="2"></div><div class="calc-summary"><div>Тариф: <span id="rate">0 ₽</span>/ч</div><div class="calc-total" id="total">0 ₽</div></div><button type="submit" class="btn btn-primary" style="width:100%">Забронировать</button></form></div></div>`,
         css: `.form-card { background:#fff; border:1px solid #ddd; border-radius:8px; padding:24px; max-width:440px; }\n.form-group { margin-bottom:14px; }\n.form-label { display:block; font-size:13px; font-weight:600; margin-bottom:5px; }\n.form-control { width:100%; padding:10px; border:1px solid #ddd; border-radius:4px; font-size:14px; font-family:inherit; }\n.calc-summary { display:flex; justify-content:space-between; align-items:center; background:#f8f9fa; border:1px solid #eee; border-radius:6px; padding:14px; margin-bottom:16px; }\n.calc-total { font-size:24px; font-weight:800; color:#007bff; }\n.btn { padding:10px 16px; font-size:14px; font-weight:600; border-radius:4px; border:none; cursor:pointer; }\n.btn-primary { background:#007bff; color:#fff; }`,
         js: `const ROOMS = [{id:'focus-1',title:'Мини-офис Focus',price:450},{id:'alpha-2',title:'Конференц-зал Alpha',price:1200},{id:'hub-3',title:'Опенспейс Hub',price:250}];\ndocument.addEventListener('DOMContentLoaded', () => {\n  const sel = document.getElementById('roomSelect');\n  const hrs = document.getElementById('hours');\n  const rate = document.getElementById('rate');\n  const total = document.getElementById('total');\n  const form = document.getElementById('bookingForm');\n  sel.innerHTML = ROOMS.map(r => '<option value="'+r.id+'" data-price="'+r.price+'">'+r.title+' ('+r.price+' ₽/ч)</option>').join('');\n  function updatePrice() {\n    const p = Number(sel.options[sel.selectedIndex].dataset.price||0);\n    const h = Math.max(1, Number(hrs.value||1));\n    rate.textContent = p+' ₽'; total.textContent = (p*h)+' ₽';\n  }\n  sel.addEventListener('change', updatePrice);\n  hrs.addEventListener('input', updatePrice);\n  updatePrice();\n  form.addEventListener('submit', (e) => { e.preventDefault(); alert('Заявка №'+Math.floor(10000+Math.random()*90000)); });\n});` } },
  { dir: '09-final', file: '01-my-bookings.md', title: 'Страница «Мои бронирования»', hl: 'js',
    exp: `# Мои бронирования\n\n## Задание\nНапишите функцию \`initMyBookings()\` с обработкой пустого состояния.`,
    s: { html: `<div style="padding:20px;font-family:'Inter',sans-serif;"><h2 style="text-align:center;margin-bottom:20px;">Мои бронирования</h2><div id="bookingsList"></div></div>`,
         css: `.booking-item { display:flex; justify-content:space-between; align-items:center; padding:14px 18px; border:1px solid #ddd; border-radius:6px; margin-bottom:10px; background:#fff; font-family:'Inter',sans-serif; }\n.empty-msg { text-align:center; padding:50px; color:#999; border:1px dashed #ddd; border-radius:8px; }`,
         js: `const MOCK_BOOKINGS = [\n  { id:48291, room:'Мини-офис Focus', date:'2026-09-10', hours:3, total:1350 },\n  { id:48292, room:'Конференц-зал Alpha', date:'2026-09-12', hours:2, total:2400 },\n];\nfunction initMyBookings() {\n  const el = document.getElementById('bookingsList');\n  if (!el) return;\n  // Если пусто — .empty-msg\n  // Иначе — рендерите .booking-item\n}\ndocument.addEventListener('DOMContentLoaded', initMyBookings);` },
    sol: { js: `const MOCK_BOOKINGS = [\n  { id:48291, room:'Мини-офис Focus', date:'2026-09-10', hours:3, total:1350 },\n  { id:48292, room:'Конференц-зал Alpha', date:'2026-09-12', hours:2, total:2400 },\n];\nfunction initMyBookings() {\n  const el = document.getElementById('bookingsList');\n  if (!el) return;\n  if (!MOCK_BOOKINGS.length) { el.innerHTML = '<div class="empty-msg">Нет бронирований</div>'; return; }\n  el.innerHTML = MOCK_BOOKINGS.map(b => '<div class="booking-item"><div><strong>'+b.room+'</strong><br><span style="font-size:13px;color:#666">'+b.date+' | '+b.hours+' ч. | №'+b.id+'</span></div><div style="text-align:right"><div style="font-size:16px;font-weight:700;color:#007bff">'+b.total+' ₽</div><span style="font-size:12px;color:#28a745">Подтверждено</span></div></div>').join('');\n}\ndocument.addEventListener('DOMContentLoaded', initMyBookings);` } },
  { dir: '09-final', file: '02-checklist.md', title: 'Финальный чек-лист', hl: 'html',
    exp: `# Финальный чек-лист (100 баллов)\n\n| Критерий | Баллы |\n|---|:---:|\n| Файловая структура (7 страниц) | 10 |\n| Семантика и стили | 10 |\n| Главная (Hero + карточки) | 10 |\n| Слайдер | 10 |\n| Динамический каталог | 15 |\n| Страница описания | 15 |\n| Поиск и сортировка | 10 |\n| Валидация форм | 10 |\n| Калькулятор | 5 |\n| Мои бронирования | 5 |\n\n**Поздравляем!** Вы собрали проект «СмартОфис» целиком!`,
    s: { html: `<div style="padding:30px;font-family:'Inter',sans-serif;text-align:center;">\n<h1 style="font-size:36px;font-weight:800;margin-bottom:16px;">Поздравляем!</h1>\n<p style="font-size:18px;color:#555;margin-bottom:30px;">Все 9 вебинаров пройдены</p>\n<div style="display:inline-flex;gap:12px;">\n<div style="background:#007bff;color:#fff;padding:16px 24px;border-radius:8px;font-weight:700;">7 страниц</div>\n<div style="background:#28a745;color:#fff;padding:16px 24px;border-radius:8px;font-weight:700;">100 баллов</div>\n<div style="background:#ff7a45;color:#fff;padding:16px 24px;border-radius:8px;font-weight:700;">HTML+CSS+JS</div>\n</div>\n</div>` } },
];

for (const step of simple) {
  writeStep(step.dir, step.file, step.title, step.hl, step.exp, step.s, step.sol);
}

console.log('Generated all step .md files!');
